######################################################################
# Automatically generated by qmake (3.0) Thu Jan 29 16:26:43 2015
######################################################################

TEMPLATE = app
TARGET = fpSim
INCLUDEPATH += .

# Input
HEADERS += DrawUtils.H worldObj.h
SOURCES += DrawUtils.cpp light.cpp qts.cpp worldObj.cpp
